# Generated by Django 3.1.6 on 2021-02-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
